#DS-CUDA SDK makefile
#By Edgar J.

include ../aux.mk

#General PATHS.......................
DSCUDACPP       ?= ../../bin/dscudacpp
CUDAPATH        ?= /usr/local/cuda/
CUDASDKPATH     ?= $(CUDAPATH)/NVIDIA_GPU_Computing_SDK
#Libraries...........................
DSCUDA_RPC			:= ../../lib/libdscuda_rpc.a
CLIB						:= -ldscuda_rpc
#Includes.............................
CUDAINCLUDES  	?= -I. -I$(CUDADIR)/include -I$(SDKDIR)/common/inc -I$(SDKDIR)/../shared/inc
#Define Enviroment Variables..........
ENVDEF					:= -DRPC_ONLY=1
# OS-specific build flag
OPENMP          := -lpthread -Xcompiler -fopenmp

#Main Body............................
TARGET = p2p

all: $(TARGET)_rpconly

$(TARGET)_rpconly:	$(TARGET).cu $(DSCUDA_RPC)
	$(DSCUDACPP) $(CUDAINCLUDES) $(ENVDEF) -o $@ -I. -i $< $(CLIB) 

clean:
	rm -rf *.o *.ptx $(TARGET)  $(TARGET)_rpconly *.linkinfo ./dscudatmp
